name: Feature Request Form
description: Suggest an idea for this software
title: "[Feature]: "
labels: [Feature Request]
assignees:
  - robertohuru
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this feature request form!
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more information?
    placeholder: E.g. email@example.com
  validations:
    required: false
- type: dropdown
  id: version
  attributes:
    label: Feature Type
    description: What is the type of your feature request? For instance, Select "Extension" if you would like us to modify existing feature.
    options:
    - Extension
    - New Feature
    - Other
  validations:
    required: true
- type: textarea
  id: problem
  attributes:
    label: Problem/Motivation
    description: Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    render: shell
  validations:
    required: false
- type: textarea
  id: solution
  attributes:
    label: Solution
    description: Describe the solution you'd like. A clear and concise description of what you want to happen.
    render: shell
  validations:
    required: true
- type: textarea
  id: alternative
  attributes:
    label: Alternative(s)
    description:  Describe alternatives you've considered. A clear and concise description of any alternative solutions or features you've considered.
    render: shell
- type: textarea
  id: screenshots
  attributes:
    label: Additional information
    description: Add any other context or screenshots about the feature request here. 
