name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g. email@example.com
    validations:
      required: false  
  - type: dropdown
    id: browsers
    attributes:
      label: Stage/Level
      description: What stage/level of the application did you encounter this error?
      multiple: false     
      options:        
        - Scheme Lodgement
        - Scheme Establishment
        - First Assessment
        - Second Assessment
        - Third Assessment
        - Import Plots
        - Search
        - Report/Certificate Generation
        - Others
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what happened!
      value: "A bug happened!"
      render: shell
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Attach Screenshots
      description: Please add screenshots of the error
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: e.g. 1.0.1
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS and Version
      description: What OS and version were you using?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
